# Generated by Django 5.0.4 on 2024-07-28 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interaction', '0002_template_sendtemplate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resources',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_class', models.TextField(blank=True, null=True)),
                ('in_car', models.TextField(blank=True, null=True)),
                ('road_test', models.TextField(blank=True, null=True)),
                ('parents', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
