# Generated by Django 5.0.4 on 2024-05-30 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainadmin', '0002_fields_rights_usertype_customuser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='home_photo',
            new_name='home_phone',
        ),
    ]
