# Generated by Django 5.0.4 on 2024-05-30 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainadmin', '0004_alter_customuser_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='birth',
            field=models.DateField(default='1999-01-01', help_text='Data of birth'),
        ),
    ]
