# Generated by Django 5.0.4 on 2024-06-09 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainadmin', '0005_alter_customuser_birth'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='uuid',
            new_name='id',
        ),
    ]
