# Generated by Django 5.0.4 on 2024-06-10 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainadmin', '0006_rename_uuid_customuser_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={},
        ),
    ]
