# Generated by Django 5.0.4 on 2024-07-28 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainadmin', '0007_alter_customuser_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertype',
            name='rights',
        ),
        migrations.AddField(
            model_name='usertype',
            name='_admin_portal',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usertype',
            name='_student_portal',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usertype',
            name='_super_user_portal',
            field=models.BooleanField(default=False),
        ),
    ]
