# Generated by Django 5.0.4 on 2024-05-12 07:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Users', '0002_initial'),
        ('configuration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student1_message', to='Users.student'),
        ),
        migrations.AddField(
            model_name='messageitems',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuration.messages'),
        ),
        migrations.AddField(
            model_name='passwordmanagement',
            name='usertype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.usertype'),
        ),
        migrations.AddField(
            model_name='rights',
            name='field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuration.fields'),
        ),
    ]
