# Generated by Django 5.0.4 on 2024-05-18 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0003_alter_companyinfo_cell_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='graphicalschedulesetting',
            name='student_details',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
