# Generated by Django 5.0.4 on 2024-06-12 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0005_graphicalschedulesetting_instructor_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyinfo',
            name='extra',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='id',
            field=models.UUIDField(editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
