# Generated by Django 5.0.4 on 2024-05-16 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0004_alter_vehicle_image_alter_vehicle_initial_mileage_and_more'),
        ('servises', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='classes',
            field=models.ManyToManyField(blank=True, related_name='Discount_classes', to='location.class'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='locations',
            field=models.ManyToManyField(blank=True, related_name='Discount_locations', to='location.location'),
        ),
        migrations.AlterField(
            model_name='services',
            name='add_ons',
            field=models.ManyToManyField(blank=True, null=True, related_name='addons', to='servises.addon'),
        ),
    ]
