# Generated by Django 5.0.4 on 2024-05-18 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servises', '0002_alter_discount_classes_alter_discount_locations_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='component',
            name='driving_hours',
        ),
        migrations.RemoveField(
            model_name='component',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='component',
            name='session_duration',
        ),
        migrations.RemoveField(
            model_name='component',
            name='start_time',
        ),
        migrations.RemoveField(
            model_name='test',
            name='timer',
        ),
    ]
