# Generated by Django 5.0.4 on 2024-05-20 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servises', '0004_component_driving_hours_component_end_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='add_ons',
            field=models.ManyToManyField(blank=True, related_name='addons', to='servises.addon'),
        ),
    ]
