# Generated by Django 5.0.4 on 2024-05-20 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servises', '0005_alter_services_add_ons'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='driving_hours',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
