# Generated by Django 5.0.4 on 2024-05-24 09:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0005_alter_howdidyouhearus_status_alter_vehicle_image'),
        ('servises', '0005_alter_services_add_ons'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='discription',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='services',
            name='key',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='services',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='component',
            name='driving_hours',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='component',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='location.location'),
        ),
    ]
