# Generated by Django 5.0.4 on 2024-05-28 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servises', '0006_services_discription_services_key_services_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='services',
            name='discription',
        ),
        migrations.AddField(
            model_name='services',
            name='description',
            field=models.TextField(default='Description 0'),
        ),
        migrations.AlterField(
            model_name='services',
            name='key',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='services',
            name='title',
            field=models.CharField(default='title 0', max_length=200),
        ),
    ]
