# Generated by Django 5.0.4 on 2024-05-21 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0004_alter_vehicle_image_alter_vehicle_initial_mileage_and_more'),
        ('servises', '0006_alter_component_driving_hours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='location.location'),
        ),
    ]
