# Generated by Django 5.0.4 on 2024-05-22 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servises', '0007_alter_component_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='discription',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='services',
            name='key',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='services',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
