# Generated by Django 5.0.4 on 2024-06-19 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servises', '0008_remove_services_description_remove_services_key_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='test',
            old_name='allow_view_complete',
            new_name='_allow_view_complete',
        ),
        migrations.RenameField(
            model_name='test',
            old_name='is_attendance_required',
            new_name='_is_attendance_required',
        ),
        migrations.RenameField(
            model_name='test',
            old_name='is_class_session',
            new_name='_is_class_session',
        ),
        migrations.RenameField(
            model_name='test',
            old_name='is_final',
            new_name='_is_final',
        ),
        migrations.RenameField(
            model_name='test',
            old_name='is_timer',
            new_name='_is_timer',
        ),
        migrations.AddField(
            model_name='test',
            name='_display_progress_bar',
            field=models.BooleanField(default=False, verbose_name='Display Progress Bar During Quiz'),
        ),
        migrations.AddField(
            model_name='test',
            name='_is_attendance_required_cr',
            field=models.BooleanField(default=False, verbose_name='Attendance Required for Preceding and Associated CR Sessions'),
        ),
        migrations.AddField(
            model_name='test',
            name='_is_attendance_required_cr_only',
            field=models.BooleanField(default=False, verbose_name='Attendance Required for All Preceding CR Sessions Only'),
        ),
        migrations.AddField(
            model_name='test',
            name='_random_order',
            field=models.BooleanField(default=False, verbose_name='Randomize Questions Order'),
        ),
    ]
