# Generated by Django 5.0.4 on 2024-07-07 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servises', '0009_rename_allow_view_complete_test__allow_view_complete_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='answers',
        ),
        migrations.AlterField(
            model_name='test',
            name='questions',
            field=models.ManyToManyField(blank=True, to='servises.question'),
        ),
        migrations.AddField(
            model_name='question',
            name='answers',
            field=models.JSONField(default=dict),
        ),
    ]
