# Generated by Django 5.0.4 on 2024-07-09 15:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servises', '0010_remove_question_answers_alter_test_questions_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_answer', models.TextField()),
                ('is_true', models.BooleanField(default=False)),
                ('score', models.PositiveIntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servises.question')),
            ],
        ),
        migrations.CreateModel(
            name='StudentTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_score', models.PositiveIntegerField(default=0)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.student')),
                ('student_answers', models.ManyToManyField(to='servises.studentquestion')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servises.test')),
            ],
        ),
    ]
