# Generated by Django 5.0.4 on 2024-07-11 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servises', '0011_studentquestion_studenttest'),
    ]

    operations = [
        migrations.AddField(
            model_name='studenttest',
            name='datetime',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='studenttest',
            name='number_correct',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='studenttest',
            name='number_wrong',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='studenttest',
            name='status',
            field=models.CharField(choices=[('PASSED', 'PASSED'), ('FAILED', 'FAILED'), ('NOT_ATTEMPTED', 'NOT_ATTEMPTED'), ('CANCELED', 'CANCELED')], default='NOT_ATTEMPTED', max_length=15),
        ),
        migrations.AddField(
            model_name='test',
            name='attempts',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
