# Generated by Django 5.0.4 on 2024-07-13 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servises', '0012_studenttest_datetime_studenttest_number_correct_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentquestion',
            name='student_answer',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
