# Generated by Django 5.0.4 on 2024-05-12 07:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Users', '0002_initial'),
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DateRange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TimeRange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(blank=True, choices=[('MON', 'Monday'), ('TUE', 'Tuesday'), ('WED', 'Wednesday'), ('THU', 'Thursday'), ('FRI', 'Friday'), ('SAT', 'Saturday'), ('SUN', 'Sunday')], max_length=3, null=True)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WeekRange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.CharField(choices=[('MON', 'Monday'), ('TUE', 'Tuesday'), ('WED', 'Wednesday'), ('THU', 'Thursday'), ('FRI', 'Friday'), ('SAT', 'Saturday'), ('SUN', 'Sunday')], max_length=15, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TimeOff',
            fields=[
                ('id', models.UUIDField(auto_created=True, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Deleted', 'Deleted'), ('Pending', 'Pending')], default='Pending', max_length=30)),
                ('code', models.CharField(blank=True, max_length=150, null=True)),
                ('type', models.CharField(choices=[('Federal Holiday', 'Federal Holiday'), ('State Holiday', 'State Holiday'), ('Religious Holiday', 'Religious Holiday'), ('Corporate Off', 'Corporate Off')], default='Corporate Off', max_length=30)),
                ('date', models.DateField(default='02/22/2024', help_text='MM/DD/YYYY')),
                ('is_all_day', models.BooleanField(default=False)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('is_assign_new_staff', models.BooleanField(default=False)),
                ('is_assign_all_staff', models.BooleanField(default=False)),
                ('note', models.TextField(blank=True)),
                ('extra', models.JSONField(blank=True)),
                ('staff', models.ManyToManyField(related_name='time_off_staff', to='Users.instructor')),
            ],
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Single Appointment(Driver Only)Road', 'Single Appointment (Driver Only)'), ('Road Test(DriverOnly)', 'Road Test (Driver Only)')], max_length=50)),
                ('date', models.DateField()),
                ('pu_location', models.CharField(max_length=200)),
                ('show_in_student_center', models.BooleanField(default=False)),
                ('slot_duration', models.IntegerField(blank=True, default=0)),
                ('slots_per_day', models.IntegerField(default=1)),
                ('date_range', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduling.daterange')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location.location')),
                ('slots', models.ManyToManyField(related_name='time_slot', to='scheduling.timerange')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointment_staff', to='Users.instructor')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location.vehicle')),
                ('week_range', models.ManyToManyField(related_name='weeks', to='scheduling.weekrange')),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student', models.ManyToManyField(related_name='apt_students', to='Users.student')),
                ('time_slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduling.timeslot')),
            ],
            options={
                'unique_together': {('time_slot', 'id')},
            },
        ),
    ]
