# Generated by Django 5.0.4 on 2024-05-16 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeoff',
            name='id',
            field=models.UUIDField(auto_created=True, blank=True, primary_key=True, serialize=False, unique=True),
        ),
    ]
