# Generated by Django 5.0.4 on 2024-05-18 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0002_alter_timeoff_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='daterange',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='daterange',
            name='start_time',
        ),
        migrations.RemoveField(
            model_name='timeoff',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='timeoff',
            name='start_time',
        ),
        migrations.RemoveField(
            model_name='timerange',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='timerange',
            name='start_time',
        ),
    ]
