# Generated by Django 5.0.4 on 2024-05-19 01:46

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0004_daterange_end_daterange_start_timeoff_end_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeslot',
            name='week_range',
        ),
        migrations.AddField(
            model_name='timeslot',
            name='week_range',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('mon', 'Monday'), ('tue', 'Tuesday'), ('wed', 'Wednesday'), ('thu', 'Thursday'), ('fri', 'Friday'), ('sat', 'Saturday'), ('sun', 'Sunday')], default='mon', max_length=15), default=list, size=None),
        ),
    ]
