# Generated by Django 5.0.4 on 2024-05-24 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0005_remove_timeslot_week_range_timeslot_week_range'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeoff',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('DELETED', 'DELETED'), ('PENDING', 'PENDING')], default='PENDING', max_length=30),
        ),
    ]
