# Generated by Django 5.0.4 on 2024-06-09 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0006_alter_timeoff_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WeekRange',
        ),
    ]
