# Generated by Django 5.0.4 on 2024-10-28 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0010_videolecture_videolecturetest_videolecturesection_and_more'),

    ]

    operations = [
        migrations.AlterField(
            model_name='videolecture',
            name='video',
            field=models.URLField(default=None),
        ),
    ]
