# Generated by Django 5.0.4 on 2024-05-12 07:55

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_id', models.IntegerField(auto_created=True, default=0)),
                ('extra', models.JSONField(blank=True, null=True)),
                ('date', models.DateField(blank=True, default='1999/01/01', null=True)),
                ('start_date', models.DateField(blank=True, default='1999/01/01', help_text='MM/DD/YYYY', null=True)),
                ('end_Data', models.DateField(default='1999/01/01', help_text='MM/DD/YYYY')),
                ('status', models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('DELETED', 'DELETED'), ('INACTIVE', 'INACTIVE')], default='ACTIVE', max_length=40)),
                ('details', models.TextField(blank=True, null=True)),
                ('note', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HowDidYouHearUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Deleted', 'Deleted'), ('Pending', 'Pending')], default='Pending', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('DELETED', 'DELETED'), ('INACTIVE', 'INACTIVE')], max_length=100)),
                ('type', models.CharField(choices=[('Main office only', ' Main office only'), ('Main office with classroom', 'Main office with classroom'), ('Class Room', 'Class Room'), ('Other (Satellite Office Only)', ' Other (Satellite Office Only)'), ('Other Classroom (Satellite Office with Classroom)', 'Other Classroom (Satellite Office with Classroom)'), ('Range', 'Range')], max_length=100)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=200)),
                ('zip', models.CharField(max_length=50)),
                ('location_manager', models.CharField(blank=True, max_length=200)),
                ('county', models.CharField(blank=True, max_length=200)),
                ('phone_main', models.CharField(max_length=100)),
                ('fax', models.CharField(blank=True, max_length=100)),
                ('other', models.CharField(blank=True, max_length=100)),
                ('location_note', models.TextField(blank=True)),
                ('has_color', models.BooleanField(default=False)),
                ('color', colorfield.fields.ColorField(blank=True, default='#FF0000', image_field=None, max_length=25, samples=None)),
                ('has_distance_based_scheduling', models.BooleanField(default=False)),
                ('distance_based_scheduling', models.IntegerField(default=0)),
                ('provider_location_id', models.CharField(blank=True, max_length=200, null=True)),
                ('send_drive_available_email_on_appointment_cancellation', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='LocationSmall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.TextField()),
                ('note', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.PositiveBigIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('note', models.TextField()),
                ('zipcode', models.IntegerField()),
                ('city', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('DELETED', 'DELETED'), ('INACTIVE', 'INACTIVE')], default='INACTIVE', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('DELETED', 'DELETED'), ('INACTIVE', 'INACTIVE')], default='INACTIVE', max_length=100)),
                ('type', models.CharField(choices=[('BUS', 'BUS'), ('CAR', 'CAR'), ('MOTORCYCLE', 'MOTORCYCLE'), ('SCHOOL BUS', 'SCHOOL BUS'), ('TANKER', 'TANKER'), ('TRACTOR TRAILER', 'TRACTOR TRAILER'), ('TRUCK', 'TRUCK')], max_length=100)),
                ('number', models.CharField(max_length=100)),
                ('make', models.CharField(max_length=150)),
                ('plate', models.CharField(max_length=100)),
                ('has_color', models.BooleanField(default=False)),
                ('color', colorfield.fields.ColorField(blank=True, default='#FF0000', image_field=None, max_length=25, samples=None)),
                ('note', models.TextField(blank=True)),
                ('asr_esn_id', models.TextField()),
                ('odometer', models.PositiveIntegerField(blank=True)),
                ('initial_mileage', models.IntegerField(blank=True)),
                ('image', models.ImageField(blank=True, storage='image/vehicles', upload_to='')),
            ],
        ),
    ]
