# Generated by Django 5.0.4 on 2024-05-12 07:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Users', '0003_initial'),
        ('location', '0001_initial'),
        ('scheduling', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='day',
            field=models.ManyToManyField(related_name='day_class', to='scheduling.timerange'),
        ),
        migrations.AddField(
            model_name='class',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Users.instructor'),
        ),
        migrations.AddField(
            model_name='class',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location.location'),
        ),
        migrations.AddField(
            model_name='location',
            name='drop_off',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dropOff', to='location.locationsmall'),
        ),
        migrations.AddField(
            model_name='location',
            name='pick_up',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pickUp', to='location.locationsmall'),
        ),
        migrations.AddField(
            model_name='school',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location.locationsmall'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='location.location'),
        ),
    ]
