# Generated by Django 5.0.4 on 2024-05-16 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0003_alter_school_address_alter_school_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='image',
            field=models.ImageField(blank=True, null=True, storage='image/vehicles', upload_to=''),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='initial_mileage',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='odometer',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
