# Generated by Django 5.0.4 on 2024-05-22 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0004_alter_vehicle_image_alter_vehicle_initial_mileage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='howdidyouhearus',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('DELETED', 'DELETED'), ('PENDING', 'PENDING')], default='PENDING', max_length=30),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='image/vehicles'),
        ),
    ]
