# Generated by Django 5.0.4 on 2024-05-25 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0005_alter_howdidyouhearus_status_alter_vehicle_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='pick_up',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='drop_off',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='LocationSmall',
        ),
    ]
