# Generated by Django 5.0.4 on 2024-06-15 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0007_alter_class_date_alter_class_end_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='howdidyouhearus',
            name='code',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='howdidyouhearus',
            name='expiration',
            field=models.DateField(default='2024-12-02'),
        ),
        migrations.AddField(
            model_name='howdidyouhearus',
            name='extra',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='howdidyouhearus',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='howdidyouhearus',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('DELETED', 'DELETED'), ('INACTIVE', 'INACTIVE')], default='INACTIVE', max_length=100),
        ),
    ]
