# Generated by Django 5.0.4 on 2024-06-15 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0008_howdidyouhearus_code_howdidyouhearus_expiration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='vin',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='asr_esn_id',
            field=models.TextField(blank=True, null=True),
        ),
    ]
