# Generated by Django 5.0.4 on 2024-05-12 07:55

import colorfield.fields
import django.db.models.deletion
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Users', '0001_initial'),
        ('configuration', '0001_initial'),
        ('location', '0001_initial'),
        ('servises', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='package',
            field=models.ManyToManyField(related_name='bill_services', to='servises.services'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='cr',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='location.class'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='package',
            field=models.ManyToManyField(related_name='enrolled_services', to='servises.services'),
        ),
        migrations.AddField(
            model_name='filecategory',
            name='package',
            field=models.ManyToManyField(related_name='package_file', to='servises.services'),
        ),
        migrations.AddField(
            model_name='files',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.filecategory'),
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Users.user')),
                ('home_pickup', models.TextField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='Male', max_length=30)),
                ('preferred_pronoun', models.CharField(choices=[('He, Him', 0), ('She, Her', 1), ('They, Them', 2)], default=0, max_length=30)),
                ('dl_permit', models.TextField(blank=True, null=True)),
                ('dl_given_date', models.DateField(blank=True, default='1999/01/01', help_text='MM/DD/YYYY', null=True)),
                ('dl_expire_date', models.DateField(blank=True, default='1999/01/01', help_text='MM/DD/YYYY', null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('medical_condition', models.TextField(blank=True, null=True)),
                ('parent_name', models.CharField(max_length=200)),
                ('parent_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('parent_phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
                ('parent_2_name', models.CharField(max_length=200)),
                ('parent_2_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('parent_2_phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
            ],
            bases=('Users.user',),
        ),
        migrations.AddField(
            model_name='files',
            name='by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_by', to='Users.user'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrolled_by', to='Users.user'),
        ),
        migrations.AddField(
            model_name='usertype',
            name='rights',
            field=models.ManyToManyField(related_name='user_rights', to='configuration.rights'),
        ),
        migrations.AddField(
            model_name='user',
            name='type',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='Users.usertype'),
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Users.user')),
                ('staff_type', models.CharField(choices=[('Instructor', 'Instructor'), ('Instructor / Teacher', 'Instructor/Teacher'), ('Junior Admin', 'Junior Admin'), ('Office Manager', 'Office Manager'), ('Owner', 'Owner'), ('Senior Admin', 'Senior Admin'), ('Teacher', 'Teacher')], default='Instructor', max_length=50)),
                ('emergency_name', models.CharField(blank=True, help_text='Emergency contact name', max_length=200, null=True)),
                ('emergency_relation', models.CharField(blank=True, help_text='Emergency  relation', max_length=200, null=True)),
                ('emergency_phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Emergency contact phone', max_length=128, null=True, region=None)),
                ('permit_number', models.CharField(blank=True, max_length=200, null=True)),
                ('car_permit_data', models.DateField(blank=True, default='1999/01/01', help_text='MM/DD/YYYY', null=True)),
                ('car_permit_expire', models.DateField(blank=True, default='1999/01/01', help_text='MM/DD/YYYY', null=True)),
                ('color', colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=25, samples=None)),
                ('zoom', models.TextField(blank=True, help_text='Link that appear in student or instructor portal to attend zoom class', null=True)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='image/staff')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='location.location')),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='location.vehicle')),
            ],
            bases=('Users.user',),
        ),
    ]
