# Generated by Django 5.0.4 on 2024-05-12 07:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Users', '0002_initial'),
        ('location', '0001_initial'),
        ('scheduling', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='working_hours',
            field=models.ManyToManyField(blank=True, related_name='staff_working_hours', to='scheduling.timerange'),
        ),
        migrations.AddField(
            model_name='student',
            name='high_school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='location.school'),
        ),
        migrations.AddField(
            model_name='student',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='location.location'),
        ),
        migrations.AddField(
            model_name='student',
            name='staff',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_staff', to='Users.instructor'),
        ),
        migrations.AddField(
            model_name='files',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='file_from', to='Users.student'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrolled_user', to='Users.student'),
        ),
        migrations.AddField(
            model_name='bill',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bill_user', to='Users.student'),
        ),
    ]
