# Generated by Django 5.0.4 on 2024-05-15 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructor',
            name='emergency_phone',
            field=models.CharField(blank=True, help_text='Emergency contact phone', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='parent_2_phone',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='parent_phone',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='cell_phone',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='home_photo',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
