# Generated by Django 5.0.4 on 2024-05-15 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0004_alter_instructor_emergency_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='parent_2_phone',
            field=models.CharField(blank=True, db_column='sd', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='preferred_pronoun',
            field=models.CharField(choices=[('He', 'He'), ('She', 'She'), ('Other', 'Other')], default=0, max_length=30),
        ),
    ]
