# Generated by Django 5.0.4 on 2024-05-24 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0005_alter_student_parent_2_phone_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='home_photo',
            new_name='home_phone',
        ),
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('DELETED', 'DELETED'), ('PENDING', 'PENDING')], default='PENDING', max_length=30),
        ),
    ]
