# Generated by Django 5.0.4 on 2024-05-30 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0006_alter_user_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='home_photo',
            new_name='home_phone',
        ),
    ]
