# Generated by Django 5.0.4 on 2024-06-09 02:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0008_remove_user_type_remove_instructor_user_ptr_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='user',
        #     name='type',
        # ),
        migrations.AlterField(
            model_name='enrollment',
            name='by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrolled_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='files',
            name='by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_by', to=settings.AUTH_USER_MODEL),
        ),
        # migrations.DeleteModel(
        #     name='CustomToken',
        # ),
    ]
