# Generated by Django 5.0.4 on 2024-06-15 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0010_drivingnote_emergencycontact_studentnote_delete_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AlterField(
            model_name='instructor',
            name='car_permit_data',
            field=models.DateField(blank=True, default='1999-01-01', help_text='MM/DD/YYYY', null=True),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='car_permit_expire',
            field=models.DateField(blank=True, default='1999-01-01', help_text='MM/DD/YYYY', null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='dl_expire_date',
            field=models.DateField(blank=True, default='1999-01-01', help_text='MM/DD/YYYY', null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='dl_given_date',
            field=models.DateField(blank=True, default='1999-01-01', help_text='MM/DD/YYYY', null=True),
        ),
    ]
