# Generated by Django 5.0.4 on 2024-06-19 03:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0011_delete_user_alter_instructor_car_permit_data_and_more'),
        ('location', '0009_vehicle_vin_alter_vehicle_asr_esn_id'),
        ('servises', '0009_rename_allow_view_complete_test__allow_view_complete_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='discount',
            field=models.ManyToManyField(blank=True, related_name='coupon', to='servises.discount'),
        ),
        migrations.AddField(
            model_name='student',
            name='_disable_self_scheduling',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='_payment_plan',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='extension_data',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='how_did_you_hear_us',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='location.howdidyouhearus'),
        ),
        migrations.AddField(
            model_name='student',
            name='information_type',
            field=models.CharField(choices=[('Teen', 'Teen'), ('Adult', 'Adult'), ('Knowledge Test', 'Knowledge Test'), ('Road Test', 'Road Test')], default='Road Test'),
        ),
    ]
