# Generated by Django 5.0.4 on 2024-06-20 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0012_bill_discount_student__disable_self_scheduling_and_more'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='user',
        #     name='_is_active',
        # ),
        # migrations.RemoveField(
        #     model_name='user',
        #     name='address',
        # ),
        # migrations.RemoveField(
        #     model_name='user',
        #     name='birth',
        # ),
        # migrations.RemoveField(
        #     model_name='user',
        #     name='cell_phone',
        # ),
        # migrations.RemoveField(
        #     model_name='user',
        #     name='city',
        # ),
        # migrations.RemoveField(
        #     model_name='user',
        #     name='code',
        # ),
        # migrations.RemoveField(
        #     model_name='user',
        #     name='email',
        # ),
        # migrations.RemoveField(
        #     model_name='user',
        #     name='first_name',
        # ),
        # migrations.RemoveField(
        #     model_name='user',
        #     name='home_phone',
        # ),
        # migrations.RemoveField(
        #     model_name='user',
        #     name='last_name',
        # ),
        # migrations.RemoveField(
        #     model_name='user',
        #     name='mid_name',
        # ),
        # migrations.RemoveField(
        #     model_name='user',
        #     name='password',
        # ),
        # migrations.RemoveField(
        #     model_name='user',
        #     name='state',
        # ),
        # migrations.RemoveField(
        #     model_name='user',
        #     name='status',
        # ),
        # migrations.RemoveField(
        #     model_name='user',
        #     name='username',
        # ),
        # migrations.RemoveField(
        #     model_name='user',
        #     name='zip',
        # ),
        # migrations.AlterField(
        #     model_name='user',
        #     name='id',
        #     field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        # ),
    ]
