# Generated by Django 5.0.4 on 2024-06-27 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0013_remove_user__is_active_remove_user_address_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instructor',
            old_name='permit_number',
            new_name='licenses',
        ),
        migrations.AddField(
            model_name='instructor',
            name='instructor_expire',
            field=models.DateField(blank=True, default='1999-01-01', help_text='MM/DD/YYYY', null=True),
        ),

    ]
