# Generated by Django 5.0.4 on 2024-06-27 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0014_rename_permit_number_instructor_licenses_and_more'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='user',
        #     name='type',
        # ),
        # migrations.DeleteModel(
        #     name='CustomToken',
        # ),
        # migrations.DeleteModel(
        #     name='User',
        # ),
    ]
